#!/usr/bin/env python3
"""Read-only structural and evidence-boundary checks for the manuscript."""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / "main.tex"


def _strip_comments(text: str) -> str:
    lines = []
    for line in text.splitlines():
        match = re.search(r"(?<!\\)%", line)
        lines.append(line[: match.start()] if match else line)
    return "\n".join(lines)


def _balanced_braces(text: str) -> bool:
    depth = 0
    index = 0
    while index < len(text):
        char = text[index]
        if char == "\\":
            index += 2
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth < 0:
                return False
        index += 1
    return depth == 0


def main() -> None:
    text = _strip_comments(MAIN.read_text(encoding="utf-8"))
    errors: list[str] = []

    if r"\renewcommand{\shorttitle}{Cross-cohort HGSOC OCM states}" not in text:
        errors.append("short running title is missing or changed")
    if not _balanced_braces(text):
        errors.append("unbalanced TeX braces in main.tex")

    begins = re.findall(r"\\begin\{([^}]+)\}", text)
    ends = re.findall(r"\\end\{([^}]+)\}", text)
    if sorted(begins) != sorted(ends):
        errors.append(f"environment mismatch: begin={begins}, end={ends}")

    inputs = re.findall(r"\\input\{([^}]+)\}", text)
    for relative in inputs:
        path = ROOT / relative
        if not path.is_file() and not path.with_suffix(".tex").is_file():
            errors.append(f"missing input: {relative}")

    labels = re.findall(r"\\label\{([^}]+)\}", text)
    duplicates = sorted({label for label in labels if labels.count(label) > 1})
    if duplicates:
        errors.append(f"duplicate labels: {duplicates}")
    for reference in re.findall(r"\\(?:ref|pageref)\{([^}]+)\}", text):
        if reference not in labels:
            errors.append(f"undefined label reference: {reference}")

    reference_text = (ROOT / "tex/references.tex").read_text(encoding="utf-8")
    bibkeys = set(re.findall(r"\\bibitem\{([^}]+)\}", reference_text))
    citations: set[str] = set()
    for group in re.findall(r"\\cite\{([^}]+)\}", text):
        citations.update(item.strip() for item in group.split(","))
    undefined = sorted(citations - bibkeys)
    if undefined:
        errors.append(f"undefined citations: {undefined}")

    for relative in (
        "tex/generated/evidence_values.tex",
        "tex/generated/cohort_table_rows.tex",
        "tex/generated/nmf_table_rows.tex",
        "tex/generated/claim_ledger_rows.tex",
        "tex/generated/failure_ledger_rows.tex",
        "tex/generated/paper_ocm_evidence_rows.tex",
        "tex/generated/study_ocm_registry_rows.tex",
    ):
        first = (ROOT / relative).read_text(encoding="utf-8").splitlines()[0]
        if "Generated by scripts/build_manuscript_evidence.py" not in first:
            errors.append(f"generated-file marker absent: {relative}")

    body_before_appendix = text.split(r"\appendix", maxsplit=1)[0]
    obsolete_overclaims = (
        "demonstrating that stable modules",
        "supports a stable core plus uncertain alternatives",
        "rank 3 is the best rank",
        "rank 3 is the true rank",
        "six non-HGSOC models remain",
    )
    for phrase in obsolete_overclaims:
        if phrase.lower() in body_before_appendix.lower():
            errors.append(f"obsolete overclaim remains in main text: {phrase}")

    with (ROOT / "evidence/numeric_ledger.tsv").open(newline="", encoding="utf-8") as handle:
        numeric_rows = list(csv.DictReader(handle, delimiter="\t"))
    numeric_ids = {row["evidence_id"] for row in numeric_rows}
    required_numeric_ids = {
        "cohort.manifest_runs",
        "cohort.primary_ocms",
        "cohort.primary_patients",
        "cohort.fastq_objects",
        "cohort.fastq_bytes",
        "cohort.one_per_patient_selections",
        "nmf.pooled.rank2.cophenetic_correlation",
        "nmf.pooled.rank3.cophenetic_correlation",
        "nmf.patient_balanced.adjusted_rand_index",
        "regulatory.grid.fit_count",
        "regulatory.patient_balanced.union_jaccard",
        "regulatory.richer.pooled.union_jaccard",
        "regulatory.alternative_optima.usable_nonempty_samples",
        "human_gem.reactions",
        "metabolic.pooled_input.sample_count",
        "tighe.table_s1.ocms",
        "meeson.public_output.rows",
        "meeson.toy.retained_set_jaccard",
    }
    if required_numeric_ids - numeric_ids:
        errors.append(f"numeric ledger missing IDs: {sorted(required_numeric_ids - numeric_ids)}")
    for row in numeric_rows:
        if not all(
            row.get(key)
            for key in (
                "evidence_id",
                "value",
                "evidence_class",
                "source_path",
                "source_locator",
                "derivation",
                "claim_limit",
            )
        ):
            errors.append(f"incomplete numeric ledger row: {row.get('evidence_id')}")

    snapshot = json.loads(
        (ROOT / "evidence/manuscript_evidence_snapshot.json").read_text(encoding="utf-8")
    )
    if snapshot["cohort"]["manifest_rows"] != 117 or snapshot["cohort"]["primary_ocms"] != 60:
        errors.append("generated evidence snapshot violates frozen cohort invariants")

    if errors:
        raise SystemExit("\n".join(f"ERROR: {error}" for error in errors))
    print(
        json.dumps(
            {
                "status": "valid",
                "inputs": len(inputs),
                "citations": len(citations),
                "labels": len(labels),
                "numeric_ledger_rows": len(numeric_rows),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
